# Generated by Django 3.0.5 on 2020-04-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingPostCode',
            new_name='billingPostcode',
        ),
    ]
