# Generated by Django 3.0.5 on 2020-04-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200419_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPostCode',
            new_name='shippingPostcode',
        ),
    ]
